// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["HybridRoscaLotteryV3"]: never
    ["IPool"]: never
    ["IVRFCoordinatorV2_5"]: never;
  }
}